on:
  push:
    branches:
      - master
  pull_request:
name: Build and Run Tests
jobs:
  buildAndRun:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - run: yarn install
        name: Install Packages using Yarn

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - run: yarn build angular-simple-oidc
        name: Build angular-simple-oidc

      - run: yarn test-lib-ci
        name: Test angular-simple-oidc

      - run: yarn build angular-simple-oidc --prod
      - run: yarn build --prod
