on: push
name: Run tests on push
jobs:
  installPackages:
    name: Install packages
    runs-on: ubuntu-18.04
    steps:
      - run: sysctl kernel.unprivileged_userns_clone=1
      - run: apt-get install libnss3
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          
      - run: yarn install
        name: Install Packages using Yarn
        
      - run: yarn build angular-simple-oidc
        name: Build angular-simple-oidc

      - name: Test angular-simple-oidc
        uses: docker://ianwalter/puppeteer:2.0.0
        with:
          entrypoint: yarn
          args: test-lib-ci

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn build --prod
